export enum Colors {
  PRIMARY_BACKGROUND = 'black',
  SECONDARY_BACKGROUND = '#1f1f21',
  PRIMARY_TEXT = 'white',
  PRIMARY_ACTIVE_BUTTON = 'blue',
  SUCCESS = '#4CAF50',
  PRIMARY_RED = 'red',
  PLACEHOLDER = '#A9A9A9',
  PRIMARY_BORDER = '#808080',
  INFO = '#7A7F80',
  DISABLED = '#CCCCCC',
  ITEM_TITLE = '#FFBA00',
}
